config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'userinfo_change/new'
  get 'userinfo_change/update'
  get 'kaimes/create'
  get 'kaimes/delete'
  get 'mode_change/new'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/change', to: 'mode_change#new'
  
  resources :menus, only: [:show, :index]
  
  resources :users do
    # GET /users/id/following, /users/id/followers の url へ route する
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts do
    member do
      # GET /microposts/id/detail, /microposts/id/reply
      get :detail, :reply
    end
  end
  
  resources :kaimes, only: [:create, :delete]
  resources :userinfo_change, only: [:new]
  resources :relationships,       only: [:create, :destroy]
  resources :reply_relationships,       only: [:create]
  resources :favorites, only: [:create, :destroy]
  
end

app/models/menu.rb
class Menu < ApplicationRecord
  
  has_many :races, dependent: :destroy
  attr_accessor :selected_date
  
  # 開催日順にソートして一つ前のMenuを返す
  def previous
    Menu.where("today_date < ?",today_date).order("today_date DESC").first
  end

  # 開催日順にソートして一つ後のMenuを返す
  def next
    Menu.where("today_date > ?",today_date).order("today_date ASC").first
  end
  
  # 当日開催される場名を取得する
  def today_course
    self.races.map(&:place).uniq
  end
  
  # 当日の引数で与えられた場名のレース一覧を取得する
  def today_selected_course_race(course_name)
    self.races.where(place: course_name)
  end

  # 当日の引数で与えられた場名、ラウンドのレースを取得する
  def get_race(course_name, round)
    self.races.where(place: course_name, round: round).first
  end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  # GET /menu/id
  def show
    
    @menu = Menu.find(params[:id])
    
    # ログイン状態の場合はマイクロポストを作成する
    if logged_in?
      @micropost = current_user.microposts.build
      @micropost.build_hosemark
    end
    
    if params[:course_name] && params[:round]
      @races = @menu.today_selected_course_race(params[:course_name])
      @race = @menu.get_race(@races.first.place, params[:round])
      @microposts = @race.microposts.where(activated: true).paginate(page: params[:page])
    else
      @races = @menu.today_selected_course_race(@menu.today_course[0])
      @race = @menu.get_race(@races.first.place, 1)
      @microposts = @race.microposts.where(activated: true).paginate(page: params[:page])
    end

  end
  
  # GET /menus
  def index
    @menus = Menu.all.order("today_date DESC").paginate(page: params[:page])
  end

end

app/helpers/menu_helper.rb
module MenuHelper
  
  # 馬印表示用のテーブルを作成する
  def create_hose_mark_tab(micropost)
    
    return [] if micropost.hosemark.nil?
    
    hose_mark = micropost.hosemark
    race = micropost.race

    hose_mark_table = { hose1: {name: race.hose1_name, hose_mark: hose_mark.hose1_mark},
           hose2: {name: race.hose2_name, hose_mark: hose_mark.hose2_mark},
           hose3: {name: race.hose3_name, hose_mark: hose_mark.hose3_mark},
           hose4: {name: race.hose4_name, hose_mark: hose_mark.hose4_mark},
           hose5: {name: race.hose5_name, hose_mark: hose_mark.hose5_mark},
           hose6: {name: race.hose6_name, hose_mark: hose_mark.hose6_mark},
           hose7: {name: race.hose7_name, hose_mark: hose_mark.hose7_mark},
           hose8: {name: race.hose8_name, hose_mark: hose_mark.hose8_mark},
           hose9: {name: race.hose9_name, hose_mark: hose_mark.hose9_mark},
           hose10: {name: race.hose10_name, hose_mark: hose_mark.hose10_mark},
           hose11: {name: race.hose11_name, hose_mark: hose_mark.hose11_mark},
           hose12: {name: race.hose12_name, hose_mark: hose_mark.hose12_mark},
           hose13: {name: race.hose13_name, hose_mark: hose_mark.hose13_mark},
           hose14: {name: race.hose14_name, hose_mark: hose_mark.hose14_mark},
           hose15: {name: race.hose15_name, hose_mark: hose_mark.hose15_mark},
           hose16: {name: race.hose16_name, hose_mark: hose_mark.hose16_mark},
           hose17: {name: race.hose17_name, hose_mark: hose_mark.hose17_mark},
           hose18: {name: race.hose18_name, hose_mark: hose_mark.hose18_mark} }
           
    hose_mark_table_sorted = []
    
    # 馬印 ◎
    hose_mark_table.each do |hose|
      hose_mark_table_sorted.push({ name: hose[1][:name], hose_mark: hose[1][:hose_mark] }) if hose[1][:hose_mark] == "◎"
    end
    
    # 馬印 ◯
    hose_mark_table.each do |hose|
      hose_mark_table_sorted.push({ name: hose[1][:name], hose_mark: hose[1][:hose_mark] }) if hose[1][:hose_mark] == "◯"
    end
    
    # 馬印 ▲
    hose_mark_table.each do |hose|
      hose_mark_table_sorted.push({ name: hose[1][:name], hose_mark: hose[1][:hose_mark] }) if hose[1][:hose_mark] == "▲"
    end
    
    # 馬印 △
    hose_mark_table.each do |hose|
      hose_mark_table_sorted.push({ name: hose[1][:name], hose_mark: hose[1][:hose_mark] }) if hose[1][:hose_mark] == "△"
    end
    
    # 馬印 ×
    hose_mark_table.each do |hose|
      hose_mark_table_sorted.push({ name: hose[1][:name], hose_mark: hose[1][:hose_mark] }) if hose[1][:hose_mark] == "×"
    end

    return hose_mark_table_sorted
    
  end
end

app/views/menus/_menu.html.erb
<li id="menu-<%= menu.id %>">
   <h2 id="select_date"><%= link_to menu.today_date.strftime("%Y年 %-m月 %-d日"), menu %></h2>
</li>

app/views/menus/index.html.erb
<h1> 開催日一覧 </h1>

<!-- マイクロポスト表示 -->
<% if @menus.any? %>
  <%= will_paginate @menus %>
  <ul class="menus">
    <%= render @menus %>
  </ul>
<% end %>

app/views/menus/show.html.erb
<!-- 開催日選択 -->
<div class="row">

  <div class="col-xs-4">
    <% if @menu.previous %>
      <%= link_to "< 前開催", menu_path(@menu.previous), class: "btn btn-lg btn-primary pull-left" %>
    <% end %>
  </div>

  <div class="col-xs-4" id="date_erea">
    <h2 id="select_date"><%= link_to @menu.today_date.strftime("%Y年 %-m月 %-d日"), menus_path %></h2>
  </div>

  <div class="col-xs-4">
    <% if @menu.next %>
      <%= link_to "次開催 >", menu_path(@menu.next), class: "btn btn-lg btn-primary pull-right"%>
    <% end %>
  </div>

</div>

<!-- 場名選択 -->
<div class="row">

  <div class="col-xs-4">
    
    <% if @menu.today_course[0] %>
      <%= link_to @menu.today_course[0], menu_path(@menu, course_name: @menu.today_course[0], round: 1), class: "btn btn-lg btn-primary w-75 center-block" %>
    <% end %>
    
  </div>

  <div class="col-xs-4">
    <% if @menu.today_course[1] %>
      <%= link_to @menu.today_course[1], menu_path(@menu, course_name: @menu.today_course[1], round: 1), class: "btn btn-lg btn-primary w-75 center-block" %>
    <% end %>
  </div>

  <div class="col-xs-4">
    <% if @menu.today_course[2] %>
      <%= link_to @menu.today_course[2], menu_path(@menu, course_name: @menu.today_course[2], round: 1), class: "btn btn-lg btn-primary w-75 center-block" %>
    <% end %>
  </div>
</div>

<!-- レース選択 -->
<div id="race_round" class="row" style="padding-top: 20px;">
  <% @races.each do |race| %>
    <div class="col-xs-1" style="padding: 1px">
      <%= link_to "#{race.round} R", menu_path(@menu, course_name: race.place, round: race.round), class: "btn btn-lg btn-primary center-block w-100" %>
    </div>
  <% end %>
</div>

<!-- レース情報 -->
<div id="race_info">
  <h1><%= @race.race_name %> <%= @race.cource_type %> <%= @race.cource_length %>m</h1>
  <!-- マイクロポスト投稿画面 -->
  <%= form_for(:micropost, url: microposts_path) do |f| %>
    <%= hidden_field_tag :race_id, @race.id %>
    <%= f.submit "レースを予想する", class: "btn btn-primary center-block" %>
  <% end %>
</div>

<!-- マイクロポスト表示 -->
<% if @race.microposts.any? %>
  <%= will_paginate @microposts %>
  <ol class="microposts">
    <%= render @microposts %>
  </ol>
<% end %>