config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'userinfo_change/new'
  get 'userinfo_change/update'
  get 'kaimes/create'
  get 'kaimes/delete'
  get 'mode_change/new'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/change', to: 'mode_change#new'
  
  resources :menus, only: [:show, :index]
  
  resources :users do
    # GET /users/id/following, /users/id/followers の url へ route する
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts do
    member do
      # GET /microposts/id/detail, /microposts/id/reply
      get :detail, :reply
    end
  end
  
  resources :kaimes, only: [:create, :delete]
  resources :userinfo_change, only: [:new]
  resources :relationships,       only: [:create, :destroy]
  resources :reply_relationships,       only: [:create]
  resources :favorites, only: [:create, :destroy]
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  
  # 各テーブルとの依存関係を定義する
  belongs_to :user, dependent: :destroy
  belongs_to :race, dependent: :destroy
  has_one :hosemark
  has_many :kaimes
  accepts_nested_attributes_for :hosemark
  accepts_nested_attributes_for :kaimes
  
  has_many :reply_relationships, class_name: "ReplyRelationship",
                                 foreign_key: "replied_post_id"
  has_many :reply_posts, through: :reply_relationships, source: :reply_post
  
  # created_at の 降順（DESC）で並び替える
  default_scope -> { order(created_at: :desc) }
  
  # リプライを受ける
  def replied(micropost)
    reply_posts << micropost
  end
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  
  # update時のみ、投稿が空出ないか確認する
  before_action :content_check, only: [:update]
  
  # GET /micropost/id
  def show
    @micropost = Micropost.find(params[:id])
    @micropost.build_hosemark
    @kaimes = @micropost.kaimes
    @kaime = Kaime.new
    @hoses = create_hose_table(@micropost.race)
  end
  
  # POST /micropost
  def create
    
    if current_user.nil?
      flash[:info] = "予想の投稿にはログインが必要です"
      redirect_to login_path
      return
    end
    
    @micropost = current_user.microposts.build()
    @micropost.race_id = params[:race_id]
    
    if @micropost.save
      # マイクロポストのshowページに遷移する
      redirect_to micropost_path(@micropost)
    else
      redirect_to root_url
    end

  end
  
  # PATCH /microposts/id
  def update
    
    @micropost = Micropost.find(params[:id])
    @micropost.update_attributes(micropost_params)
    
    # editが押下されたらactivatedをtrueに変更する。
    @micropost.update(activated: true)
    
    # 投稿したレースのmenuページに遷移する。
    race = @micropost.race
    menu = race.menu
    redirect_to menu_path(menu, course_name: race.place, round: race.round)

  end
  
  # GET /microposts/id/detail
  def detail
    @micropost = Micropost.find(params[:id])
    @microposts = @micropost.reply_posts
    render 'show_detail'
  end
  
  # GET /microposts/id/reply
  def reply
    
    if current_user.nil?
      flash[:info] = "投稿にはログインが必要です"
      redirect_to login_path
      return
    end

    @micropost = Micropost.find(params[:id])
    render 'reply'
  end
  
  private
  
    # 正しいユーザーかどうか確認
    def content_check
      if params[:micropost][:content].blank?
        @micropost = Micropost.find(params[:id])
        flash[:danger] = "投稿にはコメントの入力が必要です"
        redirect_to(micropost_path(@micropost))
      end
    end

    # strong parameter
    def micropost_params
      params.require(:micropost).permit(:content,
                                      :race_id,
                                      hosemark_attributes:[:id, 
                                      :hose1_mark,
                                      :hose2_mark,
                                      :hose3_mark,
                                      :hose4_mark,
                                      :hose5_mark,
                                      :hose6_mark,
                                      :hose7_mark,
                                      :hose8_mark,
                                      :hose9_mark,
                                      :hose10_mark,
                                      :hose11_mark,
                                      :hose12_mark,
                                      :hose13_mark,
                                      :hose14_mark,
                                      :hose15_mark,
                                      :hose16_mark,
                                      :hose17_mark,
                                      :hose18_mark])
    end

end

app/helpers/microposts_helper.rb
module MicropostsHelper

  # レーステーブルを加工して馬ハッシュを作成する
  def create_hose_table(race)
    
    hose = {hose1: {name: race.hose1_name, gate_num: race.hose1_gate_number, gate_col: race.hose1_gate_color, hose_num: race.hose1_number},
            hose2: {name: race.hose2_name, gate_num: race.hose2_gate_number, gate_col: race.hose2_gate_color, hose_num: race.hose2_number}, 
            hose3: {name: race.hose3_name, gate_num: race.hose3_gate_number, gate_col: race.hose3_gate_color, hose_num: race.hose3_number},
            hose4: {name: race.hose4_name, gate_num: race.hose4_gate_number, gate_col: race.hose4_gate_color, hose_num: race.hose4_number},
            hose5: {name: race.hose5_name, gate_num: race.hose5_gate_number, gate_col: race.hose5_gate_color, hose_num: race.hose5_number},
            hose6: {name: race.hose6_name, gate_num: race.hose6_gate_number, gate_col: race.hose6_gate_color, hose_num: race.hose6_number},
            hose7: {name: race.hose7_name, gate_num: race.hose7_gate_number, gate_col: race.hose7_gate_color, hose_num: race.hose7_number},
            hose8: {name: race.hose8_name, gate_num: race.hose8_gate_number, gate_col: race.hose8_gate_color, hose_num: race.hose8_number},
            hose9: {name: race.hose9_name, gate_num: race.hose9_gate_number, gate_col: race.hose9_gate_color, hose_num: race.hose9_number},
            hose10: {name: race.hose10_name, gate_num: race.hose10_gate_number, gate_col: race.hose10_gate_color, hose_num: race.hose10_number},
            hose11: {name: race.hose11_name, gate_num: race.hose11_gate_number, gate_col: race.hose11_gate_color, hose_num: race.hose11_number},
            hose12: {name: race.hose12_name, gate_num: race.hose12_gate_number, gate_col: race.hose12_gate_color, hose_num: race.hose12_number},
            hose13: {name: race.hose13_name, gate_num: race.hose13_gate_number, gate_col: race.hose13_gate_color, hose_num: race.hose13_number},
            hose14: {name: race.hose14_name, gate_num: race.hose14_gate_number, gate_col: race.hose14_gate_color, hose_num: race.hose14_number},
            hose15: {name: race.hose15_name, gate_num: race.hose15_gate_number, gate_col: race.hose15_gate_color, hose_num: race.hose15_number},
            hose16: {name: race.hose16_name, gate_num: race.hose16_gate_number, gate_col: race.hose16_gate_color, hose_num: race.hose16_number},
            hose17: {name: race.hose17_name, gate_num: race.hose17_gate_number, gate_col: race.hose17_gate_color, hose_num: race.hose17_number},
            hose18: {name: race.hose18_name, gate_num: race.hose18_gate_number, gate_col: race.hose18_gate_color, hose_num: race.hose18_number}
    }
    
    return hose

  end
end

app/views/microposts/_baken_type.html.erb
<table class="table table-responsive" style="white-space: nowrap">
  <tbody>
    <tr style="background:#F4D0D0">
      <td><a id="tansyo" href="javascript:void(0);">単勝</a></td>
    </tr>
    <tr style="background:#FFE2FC">
      <td><a id="hukusho" href="javascript:void(0);">複勝</a></td>
    </tr>
    <tr style="background:#E6C6F7">
      <td>
        <p style="display:inline;">馬連</p>
        <a id="umaren_nagashi" href="javascript:void(0);">ながし</a>
        <a id="umaren_box" href="javascript:void(0);">ボックス</a>
        <a id="umaren_formation" href="javascript:void(0);">フォーメーション</a>
      </td>
    </tr>
    <tr style="background:#D3D3FF">
      <td>
        <p style="display:inline;">馬単</p>
        <a id="umatan_nagashi" href="javascript:void(0);">ながし</a>
        <a id="umatan_box" href="javascript:void(0);">ボックス</a>
        <a id="umatan_formation" href="javascript:void(0);">フォーメーション</a>
      </td>
    </tr>
    <tr style="background:#ACF9FF">
      <td>
        <p style="display:inline;">ワイド</p>
        <a id="wide_nagashi" href="javascript:void(0);">ながし</a>
        <a id="wide_box" href="javascript:void(0);">ボックス</a>
        <a id="wide_formation" href="javascript:void(0);">フォーメーション</a>
      </td>
    </tr>
    <tr style="background:#C5FFC3">
      <td>
        <p style="display:inline;">三連複</p>
        <a id="sanrenpuku_nagashi1" href="javascript:void(0);">軸1頭ながし</a>
        <a id="sanrenpuku_nagashi2" href="javascript:void(0);">軸2頭ながし</a>
        <a id="sanrenpuku_box" href="javascript:void(0);">ボックス</a>
        <a id="sanrenpuku_formation" href="javascript:void(0);">フォーメーション</a>
      </td>
    </tr>
    <tr style="background:#FFF8C1">
      <td>
        <p style="display:inline;">三連単</p>
        <a id="sanrentan_nagashi1" href="javascript:void(0);">軸1頭ながし</a>
        <a id="sanrentan_nagashi2" href="javascript:void(0);">軸2頭ながし</a>
        <a id="sanrentan_box" href="javascript:void(0);">ボックス</a>
        <a id="sanrentan_formation" href="javascript:void(0);">フォーメーション</a>
      </td>
    </tr>
  </tbody>
</table>

<button type="button" id="close" class="btn btn-primary center-block">戻る</button>

<!-- 単勝 -->
<div id="modalWindow_tansho" class="modal_select_baken">  
  <%= render 'tansho' %>
</div>
<!-- 複勝 -->
<div id="modalWindow_hukusho" class="modal_select_baken">  
  <%= render 'hukusho' %>
</div>
<!-- 馬連ながし -->
<div id="modalWindow_umaren_nagashi" class="modal_select_baken">
  <%= render 'nagashi', baken_type: "馬連" %>
</div>
<!-- 馬連ボックス -->
<div id="modalWindow_umaren_box" class="modal_select_baken">
  <%= render 'box', baken_type: "馬連" %>
</div>
<!-- 馬連フォーメーション -->
<div id="modalWindow_umaren_formation" class="modal_select_baken">
  <%= render 'formation', baken_type: "馬連" %>
</div>
<!-- 馬単ながし -->
<div id="modalWindow_umatan_nagashi" class="modal_select_baken">
  <%= render 'nagashi', baken_type: "馬単" %>
</div>
<!-- 馬単ボックス -->
<div id="modalWindow_umatan_box" class="modal_select_baken">
  <%= render 'box', baken_type: "馬単" %>
</div>
<!-- 馬単フォーメーション -->
<div id="modalWindow_umatan_formation" class="modal_select_baken">
  <%= render 'formation', baken_type: "馬単" %>
</div>
<!-- ワイドながし -->
<div id="modalWindow_wide_nagashi" class="modal_select_baken">
  <%= render 'nagashi', baken_type: "ワイド" %>
</div>
<!-- ワイドボックス -->
<div id="modalWindow_wide_box" class="modal_select_baken">
  <%= render 'box', baken_type: "ワイド" %>
</div>
<!-- ワイドフォーメーション -->
<div id="modalWindow_wide_formation" class="modal_select_baken">
  <%= render 'formation', baken_type: "ワイド" %>
</div>
<!-- 三連複軸1頭ながし -->
<div id="modalWindow_sanrenpuku_nagashi1" class="modal_select_baken">
  <%= render 'nagashi', baken_type: "三連複" %>
</div>
<!-- 三連複軸2頭ながし -->
<div id="modalWindow_sanrenpuku_nagashi2" class="modal_select_baken">
  <%= render 'nagashi2', baken_type: "三連複" %>
</div>
<!-- 三連複ボックス -->
<div id="modalWindow_sanrenpuku_box" class="modal_select_baken">
  <%= render 'box', baken_type: "三連複" %>
</div>
<!-- 三連複フォーメーション -->
<div id="modalWindow_sanrenpuku_formation" class="modal_select_baken">
  <%= render 'formation', baken_type: "三連複" %>
</div>
<!-- 三連単軸1頭ながし -->
<div id="modalWindow_sanrentan_nagashi1" class="modal_select_baken">
  <%= render 'nagashi', baken_type: "三連単" %>
</div>
<!-- 三連単軸2頭ながし -->
<div id="modalWindow_sanrentan_nagashi2" class="modal_select_baken">
  <%= render 'nagashi2', baken_type: "三連単" %>
</div>
<!-- 三連単ボックス -->
<div id="modalWindow_sanrentan_box" class="modal_select_baken">
  <%= render 'box', baken_type: "三連単" %>
</div>
<!-- 三連単フォーメーション -->
<div id="modalWindow_sanrentan_formation" class="modal_select_baken">
  <%= render 'formation', baken_type: "三連単" %>
</div>

<script type="text/javascript">
  $(function() {
    $(document).ready(function () {
      // 単勝
      $("#tansyo").on('click', function () {
        $('#modalWindow_tansho').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 複勝
      $("#hukusho").on('click', function () {
        $('#modalWindow_hukusho').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 馬連ながし
      $("#umaren_nagashi").on('click', function () {
        $('#modalWindow_umaren_nagashi').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 馬連ボックス
      $("#umaren_box").on('click', function () {
        $('#modalWindow_umaren_box').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 馬連フォーメーション
      $("#umaren_formation").on('click', function () {
        $('#modalWindow_umaren_formation').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 馬単ながし
      $("#umatan_nagashi").on('click', function () {
        $('#modalWindow_umatan_nagashi').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 馬単ボックス
      $("#umatan_box").on('click', function () {
        $('#modalWindow_umatan_box').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 馬単フォーメーション
      $("#umatan_formation").on('click', function () {
        $('#modalWindow_umatan_formation').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // ワイドながし
      $("#wide_nagashi").on('click', function () {
        $('#modalWindow_wide_nagashi').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // ワイドボックス
      $("#wide_box").on('click', function () {
        $('#modalWindow_wide_box').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // ワイドフォーメーション
      $("#wide_formation").on('click', function () {
        $('#modalWindow_wide_formation').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連複軸1頭ながし
      $("#sanrenpuku_nagashi1").on('click', function () {
        $('#modalWindow_sanrenpuku_nagashi1').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連複軸2頭ながし
      $("#sanrenpuku_nagashi2").on('click', function () {
        $('#modalWindow_sanrenpuku_nagashi2').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連複ボックス
      $("#sanrenpuku_box").on('click', function () {
        $('#modalWindow_sanrenpuku_box').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連複フォーメーション
      $("#sanrenpuku_formation").on('click', function () {
        $('#modalWindow_sanrenpuku_formation').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連単軸1頭ながし
      $("#sanrentan_nagashi1").on('click', function () {
        $('#modalWindow_sanrentan_nagashi1').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連単軸2頭ながし
      $("#sanrentan_nagashi2").on('click', function () {
        $('#modalWindow_sanrentan_nagashi2').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連単ボックス
      $("#sanrentan_box").on('click', function () {
        $('#modalWindow_sanrentan_box').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
      // 三連単フォーメーション
      $("#sanrentan_formation").on('click', function () {
        $('#modalWindow_sanrentan_formation').fadeIn();
        locateCenter();  // => モーダルウィンドウを中央配置するための初期値を設定する
        $(window).resize(locateCenter);  // => ウィンドウのリサイズに合わせて、モーダルウィンドウの配置を変える
      });
    })
    
    // 「Close」ボタンをクリック時に、fadeOutメソッドでHTML要素を非表示にする
    $('.close_kaime').on('click', function() {
      $('.modal_select_baken').fadeOut();
    });
    
    // モーダルウィンドウを中央配置するための配置場所を計算する関数
    function locateCenter() {
      let w = $(window).width();
      let h = $(window).height();
    
      let cw = $('.modal_select_baken').outerWidth();
      let ch = $('.modal_select_baken').outerHeight();
   
      $('.modal_select_baken').css({
        'left': ((w - cw) / 2) + 'px',
        'top': ((h - ch) / 2) + 'px'
      });
    }
  });
</script>

app/views/microposts/_box.html.erb
<%= form_for(@kaime) do |k| %>
  <table class="table table-responsive" style="white-space: nowrap">
    <thead>
      <tr>
        <th></th>
        <th>馬番</th>
        <th>馬名</th>
      </tr>
    </thead>
    <tbody>
      <% @hoses.each do |hose| %>
        <% if !hose[1][:name].nil? %>
          <tr class='gate_<%= hose[1][:gate_col] %>'>
            <td>
              <font color="#000000">
                <%= k.check_box :first_hoses, { multiple: true, checked: hose[1][:checked], disabled: hose[1][:disabled], include_hidden: false }, hose[1][:hose_num] %>
              </font>
            </td>
            <td><%= hose[1][:hose_num] %></td>
            <td><%= hose[1][:name] %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= k.label "購入金額" %>
  <%= k.text_field :betting, class: 'form-control' %> 円
  <%= hidden_field_tag :micropost_id, @micropost.id %>
  <%= hidden_field_tag :baken_type, baken_type %>
  <%= hidden_field_tag :buy_type, "ボックス" %>
  <%= k.submit "決定", class: "btn btn-primary" %>
  <button type="button" id="close" class="btn btn-primary center-block close_kaime">戻る</button>
<% end %>

app/views/microposts/_formation.html.erb
<%= form_for(@kaime) do |k| %>
  <table class="table table-responsive" style="white-space: nowrap">
    <thead>
      <tr>
        <th>1頭目</th>
        <th>2頭目</th>
        <th>馬番</th>
        <th>馬名</th>
      </tr>
    </thead>
    <tbody>
      <% @hoses.each do |hose| %>
        <% if !hose[1][:name].nil? %>
          <tr class='gate_<%= hose[1][:gate_col] %>'>
            <td>
              <font color="#000000">
                <%= k.check_box :first_hoses, { multiple: true, checked: hose[1][:checked], disabled: hose[1][:disabled], include_hidden: false }, hose[1][:hose_num] %>
              </font>
            </td>
            <td>
              <font color="#000000">
                <%= k.check_box :second_hoses, { multiple: true, checked: hose[1][:checked], disabled: hose[1][:disabled], include_hidden: false }, hose[1][:hose_num] %>
              </font>
            </td>
            <% if baken_type.in?(['三連複', '三連単']) %>
              <td>
                <font color="#000000">
                  <%= k.check_box :third_hoses, { multiple: true, checked: hose[1][:checked], disabled: hose[1][:disabled], include_hidden: false }, hose[1][:hose_num] %>
                </font>
              </td>
            <% end %>
            <td><%= hose[1][:hose_num] %></td>
            <td><%= hose[1][:name] %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= k.label "購入金額" %>
  <%= k.text_field :betting, class: 'form-control' %> 円
  <%= hidden_field_tag :micropost_id, @micropost.id %>
  <%= hidden_field_tag :baken_type, baken_type %>
  <%= hidden_field_tag :buy_type, "フォーメーション" %>
  <%= k.submit "決定", class: "btn btn-primary" %>
  <button type="button" id="close" class="btn btn-primary center-block close_kaime">戻る</button>
<% end %>

app/views/microposts/_micropost.html.erb
<!-- micropost の パーシャル -->
<li id="micropost-<%= micropost.id %>">
  
  <div class="row">
  
    <div class="col-xs-5">
    
      <div class="profile">
        <%= image_tag micropost.user.picture.url, width: "50", height: "50" %>
        <span class="user"><%= link_to micropost.user.name, user_path(micropost.user) %></span>
      </div>
    
      <div class="hosemark">
        <ol style="list-style-type: none;">
          <% create_hose_mark_tab(micropost).each do |hose| %>
            <% if !hose[:hose_mark].blank? %>
              <li> <%= hose[:hose_mark] %> <%= hose[:name] %> </li>
            <% end %>
          <% end %>
        </ol>
      </div>
    
    </div>
    
    <div class="col-xs-7">

      <%= link_to(detail_micropost_path(micropost), class: 'list-content') do %> 
        <div class="content"><%= micropost.content %></div>
      <% end %>
      
      <div class="favorite"><%= render 'users/favorite_form', micropost: micropost if logged_in? %></div>
      
      <div class="reply">
        <% if logged_in? %>
          <%= link_to  reply_micropost_path(micropost), class: 'btn btn-default btn-xs' do %>
            <%= content_tag :span, "", class: "glyphicon glyphicon-send" %>
          <% end %>
        <% end %>
      </div>
      
      <div class="timestamp">
        <%= time_ago_in_words(micropost.created_at) %> 前
      </div>

    </div>
  
  </div>

</li>

app/views/microposts/_micropost_detail.html.erb
<div class="row" id="micropost-<%= @micropost.id %>">
  
  <div class="col-xs-5">
    
    <div class="profile">
      <%= image_tag @micropost.user.picture.url, width: "50", height: "50" %>
      <span class="user"><%= link_to @micropost.user.name, user_path(@micropost.user) %></span>
    </div>
    
    <div class="hosemark">
      <ol style="list-style-type: none;">
      <% create_hose_mark_tab(@micropost).each do |hose| %>
        <% if !hose[:hose_mark].blank? %>
          <li> <%= hose[:hose_mark] %> <%= hose[:name] %> </li>
        <% end %>
      <% end %>
      </ol>
    </div>
    
  </div>
    
  <div class="col-xs-7">
      
    <div class="kaime">
      <ol style="list-style-type: none;">
        <% @micropost.kaimes.each do |kaime| %>
          <% if !kaime[:baken_type].blank? %>
            <% if kaime.second_hoses.nil? && kaime.third_hoses.nil? %>
              <span> <%= kaime.baken_type %> <%= kaime.buy_type %> : <%= kaime.first_hoses %> <%= kaime.betting %>円 </span> </br>
            <% elsif kaime.third_hoses.nil? %>
              <span> <%= kaime.baken_type %> <%= kaime.buy_type %> : <%= kaime.first_hoses %> - <%= kaime.second_hoses %> <%= kaime.betting %>円 </span> </br>
            <% else %>
              <span> <%= kaime.baken_type %> <%= kaime.buy_type %> : <%= kaime.first_hoses %> - <%= kaime.second_hoses %> - <%= kaime.third_hoses %> <%= kaime.betting %>円 </span> </br>
            <% end %>
          <% end %>
        <% end %>
      </ol>
    </div>
    
    <div class="content"><%= @micropost.content %></div>
    <div class="favorite"><%= render 'users/favorite_form', micropost: @micropost if logged_in? %></div>
    <div class="timestamp">
      <%= time_ago_in_words(@micropost.created_at) %> 前
    </div>
  </div>
</div>

app/views/microposts/reply.html.erb
<!-- リプライ先の投稿 -->
<%= render 'microposts/micropost_detail' %>

<!-- リプライフォーム -->
<%= form_for(@micropost.reply_relationships.build) do |f| %>
  
  <div class="col-xs-5">
    <div class="profile">
      <%= image_tag current_user.picture.url, width: "50", height: "50" %>
      <span class="user"><%= current_user.name %></span>
    </div>
  </div>
    
  <div class="col-xs-7">
    <div class="field"><%= f.text_area :content %></div>
    <%= hidden_field_tag :replied_micropost_id, @micropost.id %>
    <%= f.submit "コメントする", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/microposts/show_detail.html.erb
<%= render 'microposts/micropost_detail' %>

<!-- リプライ表示 -->
<% if @microposts.any? %>
  <ol class="microposts">
    <%= render @microposts %>
  </ol>
<% end %>