config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'userinfo_change/new'
  get 'userinfo_change/update'
  get 'kaimes/create'
  get 'kaimes/delete'
  get 'mode_change/new'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/change', to: 'mode_change#new'
  
  resources :menus, only: [:show, :index]
  
  resources :users do
    # GET /users/id/following, /users/id/followers の url へ route する
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts do
    member do
      # GET /microposts/id/detail, /microposts/id/reply
      get :detail, :reply
    end
  end
  
  resources :kaimes, only: [:create, :delete]
  resources :userinfo_change, only: [:new]
  resources :relationships,       only: [:create, :destroy]
  resources :reply_relationships,       only: [:create]
  resources :favorites, only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="margin-top: 0px;">
  <small>
    <p>footer</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color:#7CC716; margin-bottom: 0px;">
<div class="container">
  <%= link_to "タイトルは未定", root_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "マイページ", user_path(current_user) %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
        <li><%= link_to "会員登録", signup_path %></li>
      <% end %>
      <li><%= link_to "会員検索", users_path %></li>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/_rails_default.html.erb
<title>KeibaSns</title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_sidebar_logged_in.html.erb
<div class="col-xs-3" style="background-color:#F0F3F5;">
  <ul class="nav nav-pills nav-stacked">
    <li class="sidebar">
      <div class="sidebar_avatars">
        <%= image_tag current_user.picture.url %>
      </div>
    </li>
    <li class="center">
      <%= link_to current_user.name, user_path(current_user) %>
    </li>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <li class="center">
      <div class="stats">
        <p>
          的中率
          <strong id="following" class="stat">
            <!-- TODO ログインユーザの的中率が表示できるようにする -->
            100%
          </strong>
        </p>
        <p>
          回収率
          <strong id="following" class="stat">
            <!-- TODO ログインユーザの回収率が表示できるようにする -->
            100%
          </strong>
        </p>
      </div>
    </li>
  </ul>
  <%= link_to "登録情報を変更する", userinfo_change_new_path, class: "btn btn-primary center-block" %>
</div>

app/views/layouts/_sidebar_logged_out.html.erb
<div class="col-xs-3" style="background-color:#F0F3F5;">
  <ul class="nav nav-pills nav-stacked">
    <li class="sidebar">
      <div class="sidebar_avatars">
        <%= image_tag "avatardefault.png" %>
      </div>
    </li>
    <li class="center">
      ゲストさん
    </li>
  </ul>
</div>

app/views/layouts/_sidebar_userpage.html.erb
<div class="col-xs-3" style="background-color:#F0F3F5;">
  <ul class="nav nav-pills nav-stacked">
    <li class="sidebar">
      <div class="sidebar_avatars">
        <%= image_tag @user.picture.url %>
      </div>
    </li>
    <li class="center">
      <%= link_to @user.name, user_path(@user) %>
    </li>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <li class="center">
      <div class="stats">
        <p>
          的中率
          <strong id="following" class="stat">
            <!-- TODO ログインユーザの的中率が表示できるようにする -->
            100%
          </strong>
        </p>
        <p>
          回収率
          <strong id="following" class="stat">
            <!-- TODO ログインユーザの回収率が表示できるようにする -->
            100%
          </strong>
        </p>
      </div>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/header' %>
  </head>
  
  <body>
    <div class="container">
     <div class="row"; width=100%;>
      <% if controller.controller_name == 'users' && controller.action_name == 'show' %>
        <%= render 'layouts/sidebar_userpage' %>
      <% elsif logged_in? %>
        <%= render 'layouts/sidebar_logged_in' %>
      <% else %>
        <%= render 'layouts/sidebar_logged_out' %>
      <% end %>
        <div class="col-xs-9">
          <!--遷移前から渡されたflash変数の表示-->
          <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>

</html>